---

versa_url: "{{ lookup('env', 'VERSA_URL') }}"
versa_username: "{{ lookup('env', 'VERSA_USERNAME') }}"
versa_password: "{{ lookup('env', 'VERSA_PASSWORD') }}"


executionItems: "{{ executionList | default([]) }}"
failedItem: "{{ currentItem }}"
