---

method: POST
username: "{{ username }}"
password: "{{ password }}"
branchName: "{{ branchName }}"
wanIpForInternet: "{{ wanIpForInternet }}"
wanIpForMpls: "{{ wanIpForMpls }}"
lanIp: "{{ lanIp }}"

deviceinfo:
  versanms.devices:
    device-list: "{{ branchName }}"

interfaceinfo:
  vni:
   name: "{{ item.portName }}"
   enable: true
   unit :
    - name: "{{ item.subInterfaceId }}"
      family:
       inet:
        address:
         - addr: "{{ item.ipAddress }}"
      enable: true
   ether-options: {}
   promiscuous: false
#url: 
#  url: "{{ https://35.165.81.59:9182/vnms/ }}"
