---

method: POST
username: "{{ username }}"
password: "{{ password }}"
branchName: "{{ branchName }}"

executionItems: "{{ executionList | default([]) }}"
failedItem: "{{ currentItem }}"

interfaceinfo:
  vni:
   name: "{{ item.portName }}"
   enable: true
   unit :
    - name: "{{ item.subInterfaceId }}"
      family:
       inet:
        address:
         - addr: "{{ item.ipAddress }}"
      enable: true
   ether-options: {}
   promiscuous: false
