---

- debug:
          msg: "Current ITEM: {{ currentServiceItem }}"

- name: Fetch Interface Information for Branch
  uri:
    url: "{{ versaUrl }}/api/config/devices/device/{{ branchName }}/config/interfaces/vni/%22{{ currentServiceItem.portName }}%22?deep"
    method: GET
    user: "{{ username }}"
    password: "{{ password }}"
    #body: "{{ interfaceinfo }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: interfaceResponse


- set_fact:
    interfaceInfo: "{{ interfaceResponse.content | from_json }}"

- debug:
          msg: "INTERFACE RESPONSE: {{ interfaceInfo }}"


#- set_fact:
#    subInterfaceId: "{{ currentServiceItem.subInterfaceId }}"

#- set_fact:
#    item.family.inet.address[0].addr: "{{ currentServiceItem.ipAddress }}"
#  with_items:  "{{ interfaceInfo.vni.unit }}"
#  when: item.name | string == subInterfaceId

- set_fact:
    inputParamsList: { 'input': '{{ currentServiceItem }}', 'interfaceInfo': '{{  interfaceInfo }}' }

- set_fact:
    interfaceInfoBody: "{{ inputParamsList | modifySubInterfaceDetails }}"
  
- debug:
          msg: "Modify interface json: {{ interfaceInfoBody }}"

- block:
  - name: Modify Branch Interface
    uri:
      url: "{{ versaUrl }}/api/config/devices/device/{{ branchName }}/config/interfaces/vni/%22{{ currentServiceItem.portName }}%22"
      method: PUT
      user: "{{ username }}"
      password: "{{ password }}"
      body: "{{ interfaceInfoBody }}"
      force_basic_auth: yes
      status_code: 204
      body_format: json
      validate_certs: no
      return_content: yes
      headers:
        Content-Type: "application/json"
        Accept: "application/json"
    register: response
- rescue:
  - debug:
      msg: "Modify Interface has failed for {{ currentServiceItem }}"
