---

- debug:
          msg: "MKA MODIFY INTERFACE LIST INPUT: {{ modifyInterfaceList }}"

- debug:
          msg: "Current ITEM: {{ currentServiceItem }}"

- name: Fetch Interface Information for Branch
  uri:
    url: "{{ versaUrl }}/api/config/devices/device/{{ branchName }}/config/interfaces/vni/%22{{ currentServiceItem.portName }}%22?deep"
    method: GET
    user: "{{ username }}"
    password: "{{ password }}"
    #body: "{{ interfaceinfo }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: interfaceResponse

- set_fact:
    interfaceInfo: "{{ interfaceResponse.content | from_json }}"

- debug:
          msg: "INTERFACE RESPONSE: {{ interfaceInfo }}"

- debug:
          msg: "INTERFACE RESPONSE2: {{ interfaceInfo.vni.unit }}"

- debug:
          msg: "INTERFACE INRRESPONSE2: {{ interfaceInfo.vni.unit[0] }}"

- debug:
          msg: "ONLY SUB-INTERFACE NAME: {{ item.name }}"
  with_items:  "{{ interfaceInfo.vni.unit }}"
  when: item.name | string == "0"

- set_fact:
    subInterfaceId: "{{ currentServiceItem.subInterfaceId }}"

- debug:
          msg: "MKA MATCHED {{ currentServiceItem.subInterfaceId }}"
  when: subInterfaceId == "0"

- set_fact:
    item.family.inet.address[0]: "{{ currentServiceItem.ipAddress }}"
  with_items:  "{{ interfaceInfo.vni.unit }}"
  when: item.name | string == subInterfaceId
  
- debug:
          msg: "INTERFACE RESPONSE3: {{ interfaceInfo.vni.unit }}"

- name: Commit changes to the Device
  uri:
    url: "{{ versaUrl }}/api/config/devices/device/{{ branchName }}/config/interfaces/vni/%22{{ item.portName }}%22"
    method: PUT
    user: "{{ username }}"
    password: "{{ password }}"
    body: "{{ interfaceinfo }}"
    force_basic_auth: yes
    status_code: 204
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
