---

- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - block: 
        - include_role:
            name: versa/versa_modify_interface_details
          private: false
          vars:
            currentServiceItem: "{{ role_item }}"
          with_items: " {{ modifyInterfaceList }}"
          loop_control:
            loop_var: "role_item"
      rescue:
         - include_vars: ../../roles/versa/versa_modify_interface_details/defaults/main.yml
         - debug:
            msg: 'SDKLOG: Modify Interface failed for {{ branchName }} with details {{ failedItem }}'
         - include_role:
             name: versa/rollback_modify_interface
           private: false
           vars:
             currentRollbackItem: "{{ role_item }}"
           with_items: " {{ executionItems }}"
           loop_control:
             loop_var: "role_item"
           when: suppressRollBack==False
         - fail:
              msg: Playbook failed to modify interface details
