---

- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - block:
        - include_role:
             name: versa/versa_modify_interface_details
          private: yes
          vars:
            currentServiceItem: "{{ role_item }}"
          with_items: " {{ modifyInterfaceList }}"
    - rescue:
        - debug:
            msg: "MKA FAIL"
          loop_control:
            loop_var: "role_item"
